-- ===========================================================================
-- Generated by scripts/refresh-images.mjs on 2026-08-28T23:12:58.891Z
--
-- Repairs 46 artwork image link(s) whose stored URL had started
-- returning HTTP 403 because the museum CDN moved the file. Each replacement was
-- re-discovered from the artwork's own stable museum object page and verified to
-- return HTTP 200 with an image/* content-type.
--
--   tier 'exact-stem' = byte-identical filename, new date folder (same file).
--   tier 'accession'  = same accession number, different rendition -> review.
--
-- Safe + idempotent: only rows whose URL actually differs are updated.
-- ===========================================================================

begin;

create temporary table _refreshed (code text primary key, url text not null, tier text not null)
  on commit drop;

insert into _refreshed (code, url, tier) values
  ('A003', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18194614/FC.691_5064.10R_MARTIN_691r2_cv_FINAL-web.jpg', 'exact-stem'),
  ('A004', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18195042/FC.459_01_H02-web.jpg', 'exact-stem'),
  ('A005', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19121721/FC.711_5064.R10R_MARTIN_711R5_p_FINAL-web.jpg', 'exact-stem'),
  ('A006', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20203650/FC.305_01_g02-web.jpg', 'exact-stem'),
  ('A007', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20200412/FC.549_5064.10R_MARTIN_549R9_FINAL-web.jpg', 'exact-stem'),
  ('A008', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/27143936/FC.605.A-B_01_f02-web.jpg', 'exact-stem'),
  ('A009', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20200322/FC.556_01_H02-web.jpg', 'exact-stem'),
  ('A010', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19121611/FC.608_01_P02-web.jpg', 'exact-stem'),
  ('A011', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/17203328/FC.499_01_P02-web.jpg', 'exact-stem'),
  ('A013', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18171610/FC.229_01_P02-web.jpg', 'exact-stem'),
  ('A014', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19121625/Warhol_E_2016_2368_REPLACEMENT_G02-web.jpg', 'exact-stem'),
  ('A015', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20200431/FC.620_01_H02-web.jpg', 'exact-stem'),
  ('A016', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/17210958/FC.616_01_H02-web.jpg', 'exact-stem'),
  ('A017', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18195118/FC.507_01_H02-web.jpg', 'exact-stem'),
  ('A019', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19185730/FC.579_10Q_MARDEN_579R2_FINAL-web.jpg', 'exact-stem'),
  ('A021', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18194745/FC.626_01_f02_FINAL-web.jpg', 'exact-stem'),
  ('A022', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/17211016/FC.625_01_P02-web.jpg', 'exact-stem'),
  ('A024', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18171843/FC.844_01_P02-web.jpg', 'exact-stem'),
  ('A025', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19121642/FC.615_01_H02-web.jpg', 'exact-stem'),
  ('A026', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18194645/FC.586_01_H02-web.jpg', 'exact-stem'),
  ('A027', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18195059/FC.460_01_P02-web.jpg', 'exact-stem'),
  ('A028', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/15225918/2000.204_01_b02-web.jpg', 'exact-stem'),
  ('A029', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20201105/FC.807_5064.Twombly_Notes_Alt_Ian%20Reeves_FINAL-web.jpg', 'exact-stem'),
  ('A030', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18210116/FC.416_01_B02_FINAL-web.jpg', 'exact-stem'),
  ('A031', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18195716/FC.824_01_B02-web.jpg', 'exact-stem'),
  ('A032', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18195203/FC.519_01_H02-web.jpg', 'exact-stem'),
  ('A033', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19211957/FC.277.A-B_01_H02-web.jpg', 'exact-stem'),
  ('A034', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20201658/FC.461_01_H02-web.jpg', 'exact-stem'),
  ('A036', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20203005/FC.738_10U_RICHTER_738R3_p-web.jpg', 'exact-stem'),
  ('A037', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20203040/FC.643_01_H02-web.jpg', 'exact-stem'),
  ('A039', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19123001/FC.293_01_H02-web.jpg', 'exact-stem'),
  ('A040', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19211930/FC.309_01_H02-web.jpg', 'exact-stem'),
  ('A041', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20201711/FC.498_10T_RICHTER_498R2-web.jpg', 'exact-stem'),
  ('A042', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18171808/FC.838.A-C_01_H02-web.jpg', 'exact-stem'),
  ('A045', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18195325/FC.475_01_P02-web.jpg', 'exact-stem'),
  ('A046', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/17211144/FC.752_5064.10J_GUSTON_752R4_HR_FINAL-web.jpg', 'exact-stem'),
  ('A047', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19185908/FC.681_01_H02-web.jpg', 'exact-stem'),
  ('A049', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19211510/FC.501_01_H02-web.jpg', 'exact-stem'),
  ('A050', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/16021110/FC.276.A-B_01_P02-web.jpg', 'accession'),
  ('A051', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/25190525/94.453.A-D_01_P02-web.jpg', 'accession'),
  ('A056', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/18194828/FC.704%20-%20primary_02-web.jpg', 'exact-stem'),
  ('A057', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19185605/FC.612_01_H02-web.jpg', 'exact-stem'),
  ('A058', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19121031/FC.604_01_H02-web.jpg', 'exact-stem'),
  ('A059', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19210948/FC.705_01_P02-web.jpg', 'exact-stem'),
  ('A061', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/20211828/FC.394_01_f02-web.jpg', 'exact-stem'),
  ('A063', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/08/19122726/FC.428.2_01_P02-web.jpg', 'exact-stem');

-- 1) The image the public tour actually reads.
update public.artwork_images ai
set url = r.url,
    review_status = case when r.tier = 'accession' then 'pending' else ai.review_status end
from _refreshed r
join public.artworks a on a.code = r.code
where ai.artwork_id = a.id
  and ai.is_current = true
  and ai.url is distinct from r.url;

-- 2) Keep the active version row (history) consistent.
update public.artwork_image_versions v
set image_url = r.url
from _refreshed r
join public.artworks a on a.code = r.code
where v.artwork_id = a.id
  and v.is_active = true
  and v.image_url is distinct from r.url;

select a.code, ai.url, ai.review_status
from public.artwork_images ai
join public.artworks a on a.id = ai.artwork_id
where ai.is_current = true and a.code in ('A003', 'A004', 'A005', 'A006', 'A007', 'A008', 'A009', 'A010', 'A011', 'A013', 'A014', 'A015', 'A016', 'A017', 'A019', 'A021', 'A022', 'A024', 'A025', 'A026', 'A027', 'A028', 'A029', 'A030', 'A031', 'A032', 'A033', 'A034', 'A036', 'A037', 'A039', 'A040', 'A041', 'A042', 'A045', 'A046', 'A047', 'A049', 'A050', 'A051', 'A056', 'A057', 'A058', 'A059', 'A061', 'A063')
order by a.code;

commit;
